#%RAML 1.0
title: customerdataverify
/sample:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"success"
              }